const USER_ROLES = {
    ADMIN: 'admin',
    CUSTOMER: 'customer',
    GUEST: 'guest',
};

const USER_STATUSES = {
    ACTIVE: 'ACTIVE',
    INACTIVE: 'INACTIVE',
    BANNED: 'BANNED',
}; 

const PRODUCT_STATUSES = {
    ACTIVE: 'ACTIVE',
    INACTIVE: 'INACTIVE',
    BANNED: 'BANNED',
    AVAILABLE: 'AVAILABLE',
    OUT_OF_STOCK: 'OUT_OF_STOCK',
    DISCONTINUED: 'DISCONTINUED',
};

const CATEGORY_STATUSES = {
    ACTIVE: 'ACTIVE',
    INACTIVE: 'INACTIVE',
    BANNED: 'BANNED',
};

const ORDER_STATUSES = {
    PENDING: 'PENDING',
    PROCESSING: 'PROCESSING',
    SHIPPING: 'SHIPPING',
    DELIVERED: 'DELIVERED',
    CANCELLED: 'CANCELLED',
    RETURNED: 'RETURNED',
    REFUNDED: 'REFUNDED',
    COMPLETED: 'COMPLETED',
    FAILED: 'FAILED',
};

const PAYMENT_METHODS = {
    // CREDIT_CARD: 'CREDIT_CARD',
    // DEBIT_CARD: 'DEBIT_CARD',
    PAYPAL: 'PAYPAL',
    VN_PAY: 'VN_PAY',
    MOMO: 'MOMO',
    COD: 'COD', // Cash on Delivery
    BANK_TRANSFER: 'BANK_TRANSFER',
};

const RATINGS = {
    ONE_STAR: 1,
    TWO_STAR: 2,
    THREE_STAR: 3,
    FOUR_STAR: 4,
    FIVE_STAR: 5,
};

const REVIEW_STATUSES = {
    PENDING: 'PENDING',
    APPROVED: 'APPROVED',
    REJECTED: 'REJECTED',
};

const REVIEW_VISIBILITY = {
    PUBLIC: 'PUBLIC',
    PRIVATE: 'PRIVATE',
};

const REVIEW_TYPES = {
    TEXT: 'TEXT',
    // IMAGE: 'IMAGE',
    // VIDEO: 'VIDEO',
};

// const COMMENT_STATUSES = {
//     APPROVED: 'APPROVED',
//     REJECTED: 'REJECTED',
//     PENDING: 'PENDING',
// };

const PAYMENT_STATUSES = {
    PENDING: 'PENDING',
    COMPLETED: 'COMPLETED',
    FAILED: 'FAILED',
    REFUNDED: 'REFUNDED',
    CANCELLED: 'CANCELLED',
    PARTIALLY_REFUNDED: 'PARTIALLY_REFUNDED',
};

const SHIPPING_METHODS = {
    FREE: 'FREE',
    FAST: 'FAST',
    STANDARD: 'STANDARD',
    // EXPRESS: 'EXPRESS',
    // OVERNIGHT: 'OVERNIGHT',
};

const SHIPPING_STATUSES = {
    PENDING: 'PENDING',
    SHIPPED: 'SHIPPED',
    // DELIVERED: 'DELIVERED',
    // RETURNED: 'RETURNED',
    // CANCELLED: 'CANCELLED',
};



module.exports = {
    USER_ROLES,
    USER_STATUSES,
    PRODUCT_STATUSES,
    CATEGORY_STATUSES,
    ORDER_STATUSES,
    PAYMENT_METHODS,
    PAYMENT_STATUSES,
    SHIPPING_METHODS,
    SHIPPING_STATUSES,
    RATINGS,
    REVIEW_STATUSES,
    REVIEW_VISIBILITY,
    REVIEW_TYPES,
    // COMMENT_STATUSES,
};

