const ADMIN_NOTIFICATIONS = {
  ORDER_NEW: 'ORDER_NEW',
  ORDER_STATUS_CHANGED: 'ORDER_STATUS_CHANGED',
  USER_REGISTERED: 'USER_REGISTERED',
  STOCK_LOW: 'STOCK_LOW',
  STOCK_OUT: 'STOCK_OUT',
  PRODUCT_REVIEWED: 'PRODUCT_REVIEWED',
};

export { ADMIN_NOTIFICATIONS };