# Stage 1: development
FROM node:20-alpine AS dev
WORKDIR /app
COPY server/package*.json ./
ENV NODE_ENV=development
RUN npm install
COPY server/ ./
CMD ["npm", "run", "dev"]

# Stage 2: production
FROM node:20-alpine AS prod
WORKDIR /app
COPY server/package*.json ./
ENV NODE_ENV=production
RUN npm install --omit=dev
COPY server/ ./
CMD ["node", "src/server.js"]
